# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advantages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Advantages', 'verbose_name_plural': 'Advantage'},
        ),
    ]
