# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Skills',
                'verbose_name_plural': 'Skill',
            },
        ),
    ]
